### ISSUE TITLE
Add hidden ssid support

### ISSUE THREAD

**Issue by mrgnou** [hypriot/flash#74]
Actually, the generated wifi configuration doesn't provide hidden ssid support.
It would be nice to manage hidden wifi networks by adding an optional param scan-ssid to device-init.yaml such as:

```
hostname: black-pearl
wifi:
  interfaces:
    wlan0:
      ssid: "MyNetwork"
      scan-ssid: 1
      password: "secret_password"
```

This way, generated wlan0 file would look like 

```
allow-hotplug wlan0

auto wlan0
iface wlan0 inet dhcp
  wpa-ssid MyNetwork
  wpa-scan-ssid 1
  wpa-psk generated_psk
```
